### ISSUE TITLE
ahbot.conf is being looked for in /etc/conf instead of /etc/mangos/conf

### ISSUE THREAD

**Issue by camjbakke** [StephenSorriaux/mangosone-docker#17]
ahbot is using a relative path of ../conf/ahbot.conf

The problem is that it is executing from /etc/mangos and this should probably be at ./conf/ahbot  (single .)

I volume mounted my ahbot.conf into /etc/conf/ahbot.conf to prove this out and it worked great.

**Comment by StephenSorriaux** [comment]
Hi,

Yes you are right, for some reason the default path is defined to `../${CONFIG_DIR}/ahbot.conf` (see https://github.com/mangoszero/server/blob/6b0e4a7228da6f609323b01871ddb9dc3ac86fcc/src/shared/SystemConfig.h.in#L100)

I just noticed that I did a mistake in the README.md file (but not in the Docker hub description...), I recommend to mount your `ahbot.conf` on `/mangosconf/ahbot.conf ` so that I set the path properly.

Thanks for reporting, the README.md file just need to be updated.
